SmartSite/ViewModels/HomeViewModel.cs
using SmartSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartSite.ViewModels
{
    public class HomeViewModel
    {
        ApplicationDbContext Context;
        public HomeViewModel()
        {
            Context = new ApplicationDbContext();
        }

        public IEnumerable<Category> GetCategories() => Context.Category.ToList();
        public Category GetSafetyCategory() => Context.Category.FirstOrDefault(c => c.CategoryName == "Safety" || c.CategoryName == "safety" || c.CategoryName =="SAFETY");
    }
}

SmartSite/Controllers/HomeController.cs
using SmartSite.DAL_Functionality;
using SmartSite.Models;
using SmartSite.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace SmartSite.Controllers
{
    public class HomeController : Controller
    {
        CategoryDAL DAL;
        ApplicationDbContext Context;
        public HomeController()
        {
            DAL = new CategoryDAL();
            Context = new ApplicationDbContext();
        }

        public ActionResult navbarPartial()
        {
            ViewBag.layoutVM = new navbarVM();
            return PartialView("_navLayout", ViewData["layoutVM"]);
        }

        public ActionResult footerPartial()
        {
            ViewBag.layoutVM = new navbarVM();
            return PartialView("_footerLayout", ViewBag.layoutVM.GetLastNews());
        }

        public ActionResult Index()
        {
            //IEnumerable<Category> allCategories = DAL.GetAllCategories();

            // random product :
            ViewBag.shownProducts = Get3Products();

            HomeViewModel viewModel = new HomeViewModel();
            
            

            navbarVM vm = new navbarVM();
            ViewBag.displayedNews = vm.GetLastNews();

            return View(viewModel);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public List<Product> Get3Products()
        {
            if (Context.Product != null && Context.Product.Count() > 2)
            {
                return Context.Product.Take(3).ToList();
            }
            else
            {
                return Context.Product.ToList();
            }
        }
 
    }
}

SmartSite/Controllers/NewsController.cs
using SmartSite.DAL_Functionality;
using SmartSite.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;

namespace SmartSite.Controllers
{
    public class NewsController : Controller
    {
        NewsDAL DAL;
        public NewsController()
        {
            DAL = new NewsDAL();
        }
        public ActionResult GetAllNews()
        {
            IEnumerable<News> allNews = DAL.GetAllNews().ToList();
            return View(allNews);
        }

        public ActionResult NewsDetails(int? id) // id = news ID
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            News news = DAL.GetNewsByID(id);
            if(news != null)
                return View(news);
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult CreateNews()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult CreateNews(News createdNews, HttpPostedFileBase UploadImg)
        {
            if (ModelState.IsValid)
            {
                if (UploadImg != null && UploadImg.ContentLength > 0)
                {
                    string ImgPath = Path.Combine(Server.MapPath("~/imageUploads/NewsImg"), UploadImg.FileName);
                    UploadImg.SaveAs(ImgPath);
                    createdNews.Image = UploadImg.FileName;

                    bool successfullyCreatingNews = DAL.CreateNews(createdNews);
                    if (successfullyCreatingNews)
                        return RedirectToAction("GetAllNews");
                    else
                        return View(createdNews);
                }
                else
                {
                    ViewBag.Message = "You have not specified a file yet ...";
                }
            }
            return View(createdNews);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult EditNews(int? id) // id = news ID
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (DAL.GetNewsByID(id) == null)
            {
                return HttpNotFound();
            }


            News modifiedNews = DAL.GetNewsByID(id);

            Session["oldImagePath"] = (Server.MapPath(Path.Combine("~/imageUploads/NewsImg", modifiedNews.Image))).ToString();
            Session["Image"] = modifiedNews.Image;

            if (modifiedNews != null)
                return View(modifiedNews);
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult EditNews(News EditedNews, HttpPostedFileBase UploadImg , string deletingImgPath)
        {
            if (ModelState.IsValid)
            {
                if (UploadImg != null && UploadImg.ContentLength > 0)
                {
                    // deleting old image from its path :
                    if (System.IO.File.Exists(deletingImgPath))
                    {
                        System.IO.File.Delete(deletingImgPath);
                    }

                    string ImgPath = Path.Combine(Server.MapPath("~/imageUploads/NewsImg"), UploadImg.FileName);
                    UploadImg.SaveAs(ImgPath);

                    
                    EditedNews.Image = UploadImg.FileName;

                    bool successfullyEditingNews = DAL.EditExistedNews(EditedNews.ID, EditedNews);
                    if (successfullyEditingNews)
                        return RedirectToAction("GetAllNews");
                    else
                        return View(EditedNews);
                }
                else
                    ViewBag.Message = "You have not specified a file yet ...";

            }
            return View(EditedNews);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteNews(int? id) // id = news ID
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            News deletedNews = DAL.GetNewsByID(id);

            Session["oldImagePath"] = (Server.MapPath(Path.Combine("~/imageUploads/NewsImg", deletedNews.Image))).ToString();

            if (deletedNews != null)
                return View(deletedNews);
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult DeleteNews(News deletedNews, string deletingImgPath)
        {
            // deleting old image from its path :
            if (System.IO.File.Exists(deletingImgPath))
            {
                System.IO.File.Delete(deletingImgPath);
            }


            bool successfullyDeletingNew = DAL.DeleteNews(deletedNews.ID);
            if (successfullyDeletingNew)
                return RedirectToAction("GetAllNews");
            else
                return View(deletedNews);
        }
    }
}

SmartSite/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using SmartSite.Models;

namespace SmartSite.Controllers
{
    // class of authodized roles :
    public class AuthorizedRoles :AuthorizeAttribute
    {
        public string roles ="Admin , User";
    }

    // ----------------------------------------------------

    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        public ActionResult Index()
        {
            var product = db.Product.Include(p => p.ProductType);
            return View(product.ToList());
        }

        [AuthorizedRoles] // authorized class for both two roles
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Product product = db.Product.Find(id);

            ViewBag.foundProductPdf = (product.PdfFile != null) ? true : false;

            if (product == null)
            {
                return HttpNotFound();
            }
            ViewData["category"] = db.Product.Find(id).ProductType.Category;
            return View(product);
        }

        // ------------------------ search product bu Name ---------------------------
        public ActionResult SearchProductByName(string productName)
        {
            if (productName==null || productName.IsEmpty())
            {
                return View("~/Views/Shared/NotFound.cshtml");
            }

            IEnumerable<Product> products = db.Product.Where(p => p.Name.Contains(productName));
            if (products != null && products.Count() > 0)
                return View(products);
            else
                return View("~/Views/Shared/NotFound.cshtml");
        }


        [Authorize(Roles = "Admin")]
        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.ProductTypeID = new SelectList(db.ProductType, "ID", "Type");
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product ,HttpPostedFileBase UploadImg , HttpPostedFileBase UploadPdf)
        {
            if (ModelState.IsValid)
            {
                if ( UploadImg != null && UploadImg.ContentLength > 0)
                {
                    // uploading image :
                    string ImgPath = Path.Combine(Server.MapPath("~/imageUploads/ProductImg"), UploadImg.FileName);
                    UploadImg.SaveAs(ImgPath);
                    product.Image = UploadImg.FileName;

                    // uploading PDF :
                    if (UploadPdf != null && UploadPdf.ContentLength > 0)
                    {
                        string pdfPath = Path.Combine(Server.MapPath("~/pdfUploads"), UploadPdf.FileName);
                        UploadPdf.SaveAs(pdfPath);
                        product.PdfFile = UploadPdf.FileName;
                    }
                    else
                    {
                        ViewBag.pdfErrorMessage = "You have not specified a file yet ...";
                    }

                    db.Product.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("FilterProductsByType", "ProductType",new { id=product.ProductTypeID});
                }
                else
                    ViewBag.imageErrorMessage = "You have not specified an image yet ...";
            }

            ViewBag.ProductTypeID = new SelectList(db.ProductType, "ID", "Type", product.ProductTypeID);
            return View(product);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            Session["oldImagePath"] = (Server.MapPath(Path.Combine("~/imageUploads/ProductImg" , product.Image))).ToString();
            if (product.PdfFile != null)
            {
                Session["oldPdfPath"] = (Server.MapPath(Path.Combine("~/pdfUploads", product.PdfFile))).ToString();
            }
            else
                Session["oldPdfPath"] =null ;

            ViewBag.ProductTypeID = new SelectList(db.ProductType, "ID", "Type", product.ProductTypeID);
            return View(product);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product, HttpPostedFileBase UploadImg, string deletingImgPath,string deletingPdfPath, HttpPostedFileBase UploadPdf)
        {
            if (ModelState.IsValid)
            {
                if ( UploadImg != null && UploadImg.ContentLength > 0)
                {
                    // deleting old image from its path :
                    if (System.IO.File.Exists(deletingImgPath))
                    {
                        System.IO.File.Delete(deletingImgPath);
                    }

                    // deleting old Pdf from its path :
                    if (System.IO.File.Exists(deletingPdfPath))
                    {
                        System.IO.File.Delete(deletingPdfPath);
                    }

                    // uploading image :
                    string ImgPath = Path.Combine(Server.MapPath("~/imageUploads/ProductImg"), UploadImg.FileName);
                    UploadImg.SaveAs(ImgPath);
                    product.Image = UploadImg.FileName;

                    // uploading PDF :
                    if (UploadPdf != null && UploadPdf.ContentLength > 0)
                    {
                        string pdfPath = Path.Combine(Server.MapPath("~/pdfUploads"), UploadPdf.FileName);
                        UploadPdf.SaveAs(pdfPath);
                        product.PdfFile = UploadPdf.FileName;
                    }
                    else
                    {
                        ViewBag.pdfErrorMessage = "You have not specified a file yet ...";
                    }

                    db.Entry(product).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("FilterProductsByType", "ProductType", new { id = product.ProductTypeID });
                }
                else
                    ViewBag.imageErrorMessage = "You have not specified an image yet ...";
            }

            ViewBag.ProductTypeID = new SelectList(db.ProductType, "ID", "Type", product.ProductTypeID);
            return View(product);
        }

        // ------------- download pdf ----------------
        public FileResult Download(string fileName)
        {
            string fullPath = Path.Combine(Server.MapPath("~/pdfUploads"), fileName);
            byte[] fileBytes = System.IO.File.ReadAllBytes(fullPath);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        private string GetFileTypeByExtension(string fileExtension)
        {
            switch (fileExtension.ToLower())
            {
                case ".docx":
                case ".doc":
                    return "Microsoft Word Document";
                case ".xlsx":
                case ".xls":
                    return "Microsoft Excel Document";
                case ".txt":
                    return "Text Document";
                case ".jpg":
                case ".png":
                    return "Image";
                case ".pdf":
                    return "PDF";
                default:
                    return "Unknown";
            }
        }


        // ---------------- delete product --------------
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);

            Session["oldImagePath"] = (Server.MapPath(Path.Combine("~/imageUploads/ProductImg", product.Image))).ToString();
            Session["oldPdfPath"] = (Server.MapPath(Path.Combine("~/pdfUploads", product.PdfFile))).ToString();

            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id , string deletingImgPath , string deletingPdfPath, HttpPostedFileBase UploadImg, HttpPostedFileBase UploadPdf)
        {
            // deleting old image from its path :
            if (System.IO.File.Exists(deletingImgPath))
            {
                System.IO.File.Delete(deletingImgPath);
            }

            // deleting old Pdf from its path :
            if (System.IO.File.Exists(deletingPdfPath))
            {
                System.IO.File.Delete(deletingPdfPath);
            }


            Product product = db.Product.Find(id);
            db.Product.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

SmartSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@*@model IEnumerable<SmartSite.Models.Category>*@
@model SmartSite.ViewModels.HomeViewModel
<!-- Hero Slider -->
<section class="hero-slider style1">
    <div class="home-slider">
        <!-- Single Slider -->
        <div class="single-slider" style="background-image: url('../../img/1.2.jpg');">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-8 col-sm-12">
                        <div class="welcome-text col-sm-12">
                            <div class="hero-text">
                                <h4>We are always ready to help you</h4>
                                <h1>Smart for Electrical Engineering</h1>
                                <div class="button">
                                    @{
                                        foreach (var category in Model.GetCategories())
                                        {
                                            <a href="@Url.Action("FilterProductTypeByCategory", "ProductType", new { id = category.ID })" class="bizwheel-btn theme-@category.ID effect">@category.CategoryName</a>
                                        }
                                    }

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ End Single Slider -->
        <!-- Single Slider -->
        <div class="single-slider" style="background-image:url('../../img/1.1.jpg')">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-8 col-sm-12">
                        <div class="welcome-text">
                            <div class="hero-text">
                                <h4>Your time is so important for us</h4>
                                <h1>Some general safety prouducts for working with</h1>
                                @if (Model.GetSafetyCategory() !=null)
                                {
                                    <div class="button">
                                        <a href="@Url.Action("FilterProductTypeByCategory", "ProductType", new { id =  Model.GetSafetyCategory().ID})" class="bizwheel-btn theme-1 effect">Safety</a>
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ End Single Slider -->
        <!-- Single Slider -->
        <div class="single-slider" style="background-image:url('../../img/1.jpg')">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-8 col-sm-12">
                        <div class="welcome-text">
                            <div class="hero-text">
                                <h4>Our experties are waiting for you</h4>
                                <h1>BE SMART, LIVE BETTER</h1>
                                <div class="p-text">
                                </div>
                                <div class="button">
                                    <a href="@Url.Action("About", "Home")" class="bizwheel-btn theme-2 effect">About us</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ End Single Slider -->
    </div>
</section>
<!--/ End Hero Slider -->
<!-- Features Area -->
<section class="features-area section-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-12">
                <!-- Single Feature -->
                <div class="single-feature">
                    <div class="icon-head"><i class="fa fa-podcast"></i></div>
                    <h4>High-quality service</h4>
                </div>
                <!--/ End Single Feature -->
            </div>
            <div class="col-lg-3 col-md-6 col-12">
                <!-- Single Feature -->
                <div class="single-feature">
                    <div class="icon-head"><i class="fa fa-podcast"></i></div>
                    <h4>Quality Products</h4>
                </div>
                <!--/ End Single Feature -->
            </div>
            <div class="col-lg-3 col-md-6 col-12">
                <!-- Single Feature -->
                <div class="single-feature active">
                    <div class="icon-head"><i class="fa fa-podcast"></i></div>
                    <h4>continuous support</h4>

                </div>
                <!--/ End Single Feature -->
            </div>
            <div class="col-lg-3 col-md-6 col-12">
                <!-- Single Feature -->
                <div class="single-feature">
                    <div class="icon-head"><i class="fa fa-podcast"></i></div>
                    <h4>latest news</h4>
                </div>
                <!--/ End Single Feature -->
            </div>
        </div>
    </div>
</section>
<!--/ End Features Area -->
<!-- Call To Action -->
<section class="call-action overlay" style="background-image:url('')">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-12">
                <div class="call-inner">
                    <h2>BE SMART, LIVE BETTER</h2>
                    <p>our promise to our customers who have adopted continuous, high-quality service and products.</p>
                </div>
            </div>

        </div>
    </div>
</section>
<!--/ End Call to action -->
<!-- Services -->
<section class="services section-bg section-space">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title style2 text-center">
                    <div class="section-top">
                        <h1><span>Sample of our products</span><b>Products We Provide</b></h1>
                    </div>
                    <div class="section-bottom">
                        <div class="text-style-two">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

            <!-- Single Service -->
            @{
                List<SmartSite.Models.Product> randomProducts = ViewBag.shownProducts;
                if (randomProducts != null)
                {
                    foreach (var product in randomProducts)
                    {
                        <div class="col-lg-4 col-md-4 col-12">
                            <div class="single-service">
                                <div class="service-head">
                                    <img src="~/imageUploads/ProductImg/@product.Image" alt="#">
                                    <a href="@Url.Action("Details","Products",new { id=product.ID})"><div class="icon-bg"><i class="fas fa-arrow-right"></i></div></a>
                                </div>
                                <div class="service-content">
                                    <h4><a href="@Url.Action("Details","Products",new { id=product.ID})">@product.Name</a></h4>
                                    <a class="btn" href="@Url.Action("Details","Products",new { id=product.ID})"><i class="fas fa-arrow-circle-right"></i>More Details</a>
                                </div>
                            </div>
                        </div>
                    }
                }
            }


            <!--/ End Single Service -->

        </div>
    </div>
</section>
<!--/ End Services -->
<!-- Latest Blog -->
<section class="latest-blog section-space">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-12">
                <div class="section-title default text-center">
                    <div class="section-top">
                        <h1><span>Published</span><b>Latest News</b></h1>
                    </div>
                    <div class="section-bottom">
                        <div class="text">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="blog-latest blog-latest-slider">
                    @{
                        if (ViewBag.displayedNews != null)
                        {
                            foreach (var news in ViewBag.displayedNews)
                            {
                                <!-- Single Blog -->
                                <div class="single-news ">
                                    <div class="news-head overlay">
                                        <span class="news-img" style="background-image:url('../../imageUploads/NewsImg/@news.Image');height:200px"></span>
                                        <a href="@Url.Action("NewsDetails","News",new { id= news.ID})" class="bizwheel-btn theme-2">Read more</a>
                                    </div>
                                    <div class="news-body">
                                        <div class="news-content">
                                            <h3 class="news-title"><a href="@Url.Action("NewsDetails","News",new { id= news.ID})">@news.Title</a></h3>
                                            <div class="news-text">
                                                <p style="height:50px;overflow:hidden">@news.Details</p>
                                            </div>
                                            <ul class="news-meta">
                                                <li class="date"><i class="fa fa-calendar"></i>@news.Date.ToString("yyyy-MM-dd")</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <!--/ End Single Blog -->

                            }
                        }
                    }

                </div>
            </div>
        </div>
    </div>
</section>
<!--/ End Latest Blog -->
<!-- Client Area -->
<div class="clients section-bg">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="partner-slider">
                    <!-- Single client -->
                    <div class="single-slider">
                        <div class="single-client">
                            <a href="#" target="_blank"><img src="~/img/client/client-1.png" alt="#"></a>
                        </div>
                    </div>
                    <!--/ End Single client -->
                    <!-- Single client -->
                    <div class="single-slider">
                        <div class="single-client">
                            <a href="#" target="_blank"><img src="~/img/client/client-2.png" alt="#"></a>
                        </div>
                    </div>
                    <!--/ End Single client -->
                    <!-- Single client -->
                    <div class="single-slider">
                        <div class="single-client">
                            <a href="#" target="_blank"><img src="~/img/client/client-3.png" alt="#"></a>
                        </div>
                    </div>
                    <!--/ End Single client -->
                    <!-- Single client -->
                    <div class="single-slider">
                        <div class="single-client">
                            <a href="#" target="_blank"><img src="~/img/client/client-4.png" alt="#"></a>
                        </div>
                    </div>
                    <!--/ End Single client -->
                    <!-- Single client -->
                    <div class="single-slider">
                        <div class="single-client">
                            <a href="#" target="_blank"><img src="~/img/client/client-5.png" alt="#"></a>
                        </div>
                    </div>
                    <!--/ End Single client -->
                    <!-- Single client -->
                    <div class="single-slider">
                        <div class="single-client">
                            <a href="#" target="_blank"><img src="~/img/client/client-6.png" alt="#"></a>
                        </div>
                    </div>
                    <!--/ End Single client -->
                    <!-- Single client -->
                    <div class="single-slider">
                        <div class="single-client">
                            <a href="#" target="_blank"><img src="~/img/client/client-7.png" alt="#"></a>
                        </div>
                    </div>
                    <!--/ End Single client -->
                    <!-- Single client -->
                    <div class="single-slider">
                        <div class="single-client">
                            <a href="#" target="_blank"><img src="~/img/client/client-8.png" alt="#"></a>
                        </div>
                    </div>
                    <!--/ End Single client -->
                    <!-- Single client -->
                    <div class="single-slider">
                        <div class="single-client">
                            <a href="#" target="_blank"><img src="~/img/client/client-9.png" alt="#"></a>
                        </div>
                    </div>
                    <!--/ End Single client -->


                </div>
            </div>
        </div>
    </div>
</div>
<!--/ End Client Area -->